global:
  imageK8S: hashicorp/consul-k8s:0.26.0 
  image: hashicorp/consul:1.10.0 
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
controller:
  enabled: true
server:
  replicas: 1
connectInject:
  enabled: true
ui:
  enabled: true
