global:
  imageK8S: kschoche/consul-k8s-dev
  image: hashicorp/consul:1.10.0-beta4 
  tls:
    enabled: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
controller:
  enabled: true
server:
  replicas: 1
connectInject:
  enabled: true
ui:
  enabled: true
